### ISSUE TITLE
onProgress参数int型

### ISSUE THREAD

**Issue by wurensen** [Aspsine/MultiThreadDownload#21]
还没开始用，不过看到下载中的参数为int型，对于文件下载，这个长度应该不够吧？

**Comment by Aspsine** [comment]
谢谢提醒。
java int的取值范围是[-2147483648, 2147483647]，大概能存下1.9G大小的文件。
我争取在这周修复这个问题。

**Comment by Aspsine** [comment]
#22 
Fixed.
