### ISSUE TITLE
小哥装上您的多线程下载的Demo 报空指针的错误 所有jar和依赖工程都加好了

### ISSUE THREAD

**Issue by maobon** [Aspsine/MultiThreadDownload#28]
反复clean 工程没有报错的情况下 传到手机上运行报错 但是直接下载demo.apk 就可以正常运行 麻烦您看下 多谢多谢！

**Comment by Aspsine** [comment]
你用的Eclipse？
请提供一下logcat里面的错误信息。

**Comment by maobon** [comment]
您好 可否告诉我下您的QQ 多谢
----- 原始邮件 -----
发件人：Running man! <notifications@github.com>
收件人：Aspsine/MultiThreadDownload <MultiThreadDownload@noreply.github.com>
抄送人：Bob <xinyi880910@vip.sina.com>
主题：Re:_[MultiThreadDownload]_小哥装上您的多线程下载的Demo_报空指针的错误_所有jar和依赖工程都加好了_(#28)
日期：2015年10月09日 15点33分

你用的Eclipse？

请提供一下logcat里面的错误信息。

&mdash;

**Comment by Aspsine** [comment]
有问题都集中在issue里面提吧，解决了你的问题。别人遇到相同的问题也可以参考。
