### ISSUE TITLE
收到下载完成通知但是拿到的process还是90%

### ISSUE THREAD

**Issue by wszyquan** [Aspsine/MultiThreadDownload#32]
这个问题经常出现

**Comment by Aspsine** [comment]
目前在thunder分支有我重构的一个版本，目前还没有合并的主分支，麻烦使用
https://raw.githubusercontent.com/Aspsine/MultiThreadDownload/thunder/art/demo.apk
再做测试。
测试过程中需要注意：
腾讯家的几个app可能都不支持断点续传，是因为这几个连接都不支持正规的http分段下载文件的协议。

**Comment by wszyquan** [comment]
收到，谢谢
