### ISSUE TITLE
对于不支持range的服务器,您是如何做到暂停和下载的

### ISSUE THREAD

**Issue by itsmallsun** [Aspsine/MultiThreadDownload#45]
您这个下载框架中对于不支持range的服务器你这个也可以做到暂停和恢复,您这个是如何做到的？

**Comment by Aspsine** [comment]
这里是我之前判断http uri是否支持断点续传的方法：
https://github.com/Aspsine/MultiThreadDownload/blob/a29a4f238f43ac156a731deaab5c48287597cfd5/library/src/main/java/com/aspsine/multithreaddownload/core/ConnectTaskImpl.java#L111
```java
final boolean isAcceptRanges;
String acceptRanges = httpConnection.getHeaderField("Accept-Ranges");
if (acceptRanges != null) {
     isAcceptRanges = acceptRanges.equals("bytes");
} else {
     isAcceptRanges = false;
}
```
但是某天一个朋友提issue说，对于某些链接无法暂停下载。#34

于是我仔细查看了一下 RFC DOC：http://www.w3.org/Protocols/rfc2616/rfc2616.txt

将判断方式修改为：
https://github.com/Aspsine/MultiThreadDownload/blob/master/library/src/main/java/com/aspsine/multithreaddownload/core/ConnectTaskImpl.java#L83

```java
httpConnection.setRequestProperty("Range", "bytes=" + 0 + "-");
final int responseCode = httpConnection.getResponseCode();
if (responseCode == HttpURLConnection.HTTP_OK) {
         //isAcceptRanges = ture
         parseResponse(httpConnection, false);
} else if (responseCode == HttpURLConnection.HTTP_PARTIAL) {
        //isAcceptRanges = false
        parseResponse(httpConnection, true);
} else {
        throw new DownloadException(DownloadStatus.STATUS_FAILED, "UnSupported response code:" + responseCode);
}
```

至于为什么作出这样的修改，你可以仔细察看一些#34 中我引用RFC文档中的内容。

**Comment by itsmallsun** [comment]
谢谢您，我大概懂了 在http1.1中可以请求该实体的一个或多个子范围，而不是
整个实体，使用范围请求头，就可以得到,是这样吗 ？

**Comment by itsmallsun** [comment]
还想请问您一个问题,当多线程下载时,其中的一个线程死掉了,需要重新创建线程去下载，您这一步是怎么做的？

**Comment by zewar888** [comment]
程序写的很有水准，有很多值得学习的地方，感谢你的分享，我也是遇到了暂停延时很久的问题，还有就是非正常关闭，下载的进度又回到先前的进度，谢谢！

**Comment by Aspsine** [comment]
@zewar888 fixed
