### ISSUE TITLE
Migration from previous versions have to been implemented

### ISSUE THREAD

**Issue by risayew** [Aspsine/MultiThreadDownload#47]
Hi, Thank you for the great library.
I updated the library and have the following error message in my app W/System.err﹕ android.database.sqlite.SQLiteException: no such column: tag (code 1): , while compiling: select * from ThreadInfo where tag = ?
...

**Comment by Aspsine** [comment]
You can update db version.
https://github.com/Aspsine/MultiThreadDownload/blob/master/library/src/main/java/com/aspsine/multithreaddownload/db/DBOpenHelper.java#L13

```java
private static final int DB_VERSION = 2;
```
