### ISSUE TITLE
Throws Download exception with some available link

### ISSUE THREAD

**Issue by nanashi1111** [Aspsine/MultiThreadDownload#49]
I'm trying download some image from facebook use your library. But when i download, i found some links that your library can't download. It failed with DownloadException. Error message is "File error".
But when i download with an internet browser, i found no problem. Please check, thank you :)

Example: https://scontent.xx.fbcdn.net/hphotos-xlf1/v/t1.0-9/p720x720/12187696_986062654801567_4375931215754732524_n.jpg?oh=4ba7f5ce982629f94d6a8bd8a21cb879&oe=5744E33C

**Comment by Aspsine** [comment]
File can not be created in your sd card maybe sd card was mounted.
