### ISSUE TITLE
Video download not working

### ISSUE THREAD

**Issue by manojprithvee** [Aspsine/MultiThreadDownload#52]
downloaded videos cannot be played

**Comment by tikkat3** [comment]
i have the same issue，but i fix it 
Look the " DonwloadService"     line 113

 private void download(final int position, final AppInfo appInfo, String tag) {
        final DownloadRequest request = new DownloadRequest.Builder()
                .setTitle(appInfo.getName() + ".apk")
                .setUri(appInfo.getUrl())
                .setFolder(mDownloadDir)
                .build();
        mDownloadManager.download(request, tag, new DownloadCallBack(position, appInfo, mNotificationManager, getApplicationContext()));
    }
modified suffix to ".mp4"
