### ISSUE TITLE
取消下载监听，但是不取消下载

### ISSUE THREAD

**Issue by chenwulue** [Aspsine/MultiThreadDownload#54]
比如我在单个页面，点击了下载操作，同时这里有进度条以及下载完成后的控件变化等。但是我希望，我点击返回后，这个是要继续下载的，只是不需要监听进度了。当前的是会继续监听，导致空指针错误

**Comment by butterfly-fly** [comment]
不监听进入，再次进入页面，进度条如何显示？

**Comment by Aspsine** [comment]
#71
