### ISSUE TITLE
resume functionality is not working for larger file size

### ISSUE THREAD

**Issue by mkaarthick** [Aspsine/MultiThreadDownload#59]
Hi, resume is not working properly. I'm trying to download a .obf file size of 220 mb. I paused it and after resuming, it restarting the download from the beginning.

**Comment by Aspsine** [comment]
Maybe the link doesn't support http `range` header filed. 

You can checkout out `isRangeSupport`. 

```java
 @Override
    public void onConnected(long total, boolean isRangeSupport) {

    }
```
