### ISSUE TITLE
下载过程中，离开界面后台下载，再次回到下载列表，现在进度怎么再次显示出来

### ISSUE THREAD

**Issue by huanting** [Aspsine/MultiThreadDownload#62]
在下载列表界面下载，然后离开该界面后台开始下载，如果再次进入下载列表界面，怎么显示当前下载的进度。 因为这个lib使用的是callback，怎么跟新到这个下载task中

**Comment by Aspsine** [comment]
@huanting 
参考
https://github.com/Aspsine/MultiThreadDownload/blob/master/app/src/main/java/com/aspsine/multithreaddownload/demo/ui/fragment/ListViewFragment.java

**Comment by huanting** [comment]
参考上面代码，已经实现，谢谢！
