### ISSUE TITLE
how to get progress from download thread?

### ISSUE THREAD

**Issue by yasaman93** [Aspsine/MultiThreadDownload#71]
How can I solve this problem?
I click on download button in activity X and use your download library, then I press back button and go to previous activity, download is continued in background. Then I go to activity X again and I want my progress bar show continued download, but it can't show it! 
what can I do for this? I know that download is on progress but my progress bar can't set its progress...
please help :(
this does't worked: DownloadManager.getInstance().getDownloadProgress("test1.mp3").getProgress()

**Comment by Aspsine** [comment]
https://github.com/Aspsine/MultiThreadDownload/blob/master/app/src/main/java/com/aspsine/multithreaddownload/demo/ui/fragment/ListViewFragment.java

**Comment by Hitexroid** [comment]
`downloadInfo.getProgress()` always null
