### ISSUE TITLE
Delete file and remove thread from database

### ISSUE THREAD

**Issue by sajadmartiny** [Aspsine/MultiThreadDownload#72]
hi , how to remove one thread from database when file not downloading full , and adding again not downloading continuation

**Comment by Aspsine** [comment]
You want to not resuming the download when you start download with the same tag again?

```java
if(DownloadManager.getInstance(). isRunning(tag)){
    // has callback
    DownloadManager.getInstance().cancel(tag);
}else{
    // no callback
    DownloadManager.delete(tag);
}
```
I made some changes last night and fix some bugs. Make sure to use the latest version.

**Comment by sajadmartiny** [comment]
public void delete(String tag) {
        DownloadInfo downloadInfo = getDownloadInfo(tag);
        if (downloadInfo != null) {
            File file = new File(downloadInfo.getDir(), downloadInfo.getName());
            if (file.exists() && file.isFile()) {
                file.delete();
            }
        }
        mDBManager.delete(tag);
    }

return exception because downloadInfo.getName  return null

**Comment by Aspsine** [comment]
```java
final DownloadRequest request = new DownloadRequest.Builder()
            .setName(appInfo.getName() + ".apk")
            .setUri(appInfo.getUrl())
            .setFolder(mDownloadDir)
            .build();
```
Did your `setName(...)`?

**Comment by sajadmartiny** [comment]
yes i set name  but  i am fix it  whit 
 public void delete(String tag) {
        String key = createKey(tag);
        mDBManager.delete(key);
    } 

and Thanks you for library
