### ISSUE TITLE
Protocol error for one of my urls!

### ISSUE THREAD

**Issue by yasaman93** [Aspsine/MultiThreadDownload#78]
I can download many files with your library, but for one of download urls I got protocol error!
this is my url: 
http://med.mediana.ir/sources/books/files/1395/001-%20John%20Henry.mp3

error: fail audiocom.aspsine.multithreaddownload.DownloadException: Protocol error

**Comment by Aspsine** [comment]
I tested. It works fine.

John Henry's story is very interesting. : )

**Comment by yasaman93** [comment]
I found my problem!
I must replace spaces in url with %20 programmatically! :)
